### ISSUE TITLE
babel-register fails to fetch its dependencies

### ISSUE THREAD

**Issue by hylkevds** [SensorThings-Dashboard/SensorThings-Dashboard#1]
When running `npm install` for the first time, babel-register fails to fetch its dependencies
```
├─┬ gulp-babel-istanbul@1.6.0 
│ ├── UNMET PEER DEPENDENCY babel-core@6.24.1
│ └─┬ babel-istanbul@0.12.2 
│   ├── abbrev@1.0.9 
│   ├── esprima@2.7.3 
│   ├─┬ handlebars@4.0.8 
│   │ ├── source-map@0.4.4 
│   │ └─┬ uglify-js@2.8.22 
│   │   └─┬ yargs@3.10.0 
│   │     └── window-size@0.1.0 
│   ├─┬ js-yaml@3.8.3 
│   │ ├─┬ argparse@1.0.9 
│   │ │ └── sprintf-js@1.0.3 
│   │ └── esprima@3.1.3 
│   ├─┬ multi-glob@1.0.1 
│   │ ├── glob@5.0.15 
│   │ └── lodash@3.10.1 
│   ├── nopt@3.0.6 
│   ├── source-map@0.4.4 
│   ├── supports-color@3.1.2 
│   ├─┬ which@1.2.14 
│   │ └── isexe@2.0.0 
│   └── wordwrap@1.0.0 
```
The first run of gulp then fails:
```
[10:05:30] Requiring external module babel-register
/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/babel-register/lib/node.js:103
  var opts = new _babelCore.OptionManager().init((0, _extend2.default)({ sourceRoot: _path2.default.dirname(filename) }, (0, _cloneDeep2.default)(transformOpts), { filename: filename }));
             ^

TypeError: _babelCore.OptionManager is not a function
    at compile (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/babel-register/lib/node.js:103:14)
    at loader (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/liftoff/index.js:198:16)
    at module.exports (/home/scf/NetBeansProjects/SensorThings/SensorThingsDashboard/node_modules/flagged-respawn/index.js:17:3)
```

Only after manually running `npm install babel-register` does it properly install:
```
iot-dashboard-iosb@1.0.0 .../SensorThingsDashboard
├─┬ babel-cli@6.24.1
│ └── babel-core@6.24.1 
└─┬ babel-register@6.24.1
  └── babel-core@6.24.1 
```
Any clue why this is?

**Comment by siboehm** [comment]
Couldn't recreate the issue, I did a fresh setup of the Repo and fetched the dependencies with `npm install`, babel-register installed properly. Anyone else experiencing this issue?

**Comment by hylkevds** [comment]
Strangely, a second run of `npm install` does finish the installation of the missing dependencies. It's probably a problem om npm itself.
